[features]
seeds = false
[programs.localnet]
mark_two = "93iacsFnFj4G7ae1psGCRGzA2XmQSAJ7bFBVchxZ5qFL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/harsh/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
